global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product-order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-order-service:8888']
